### ISSUE TITLE
Cursors: not working yet in the migration, plus they have the wrong name and defineRelatedType is 👎

### ISSUE THREAD

**Issue by boutell** [apostrophecms/code-upgrader#4]
Definitions of related types (cursors) got lost in the apostrophe-pieces parse. Figure out what to do about them.

**Comment by boutell** [comment]
In addition to being busted right now, I think defineRelatedType in general can probably be eliminated in favor of a simpler way of handling this, as long as there's a "query" section in index.js to implement the former "cursor filters" (aka "query features") in.

**Comment by abea** [comment]
Close, right @boutell ?
